config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 get  "/" =>  "quests#index"
 get  "quests/test" => "quests#test"
 root 'quests#index'
 resources :clist
 resources :quests do
 	resources :units
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clist.rb
class Clist < ApplicationRecord
end

app/models/player.rb
class Player < ApplicationRecord
end

app/models/quest.rb
class Quest < ApplicationRecord
	has_many :units
end

app/models/unit.rb
class Unit < ApplicationRecord
	belongs_to :quest
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	before_action :configure_permitted_parameters, if: :devise_controller?
	before_action :authenticate_user!

	  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/clist_controller.rb
class ClistController < ApplicationController

def new

	@clist = Clist.new

end

def create

end

def edit

end

def show

end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController

def authentificate
  before_action :authenticate_user!
end


def new

	@quest = Quest.new

end

def create
    @quest = Quest.new(quest_params)
  

      if  @quest.save
   
        redirect_to quests_path
      else
        render action: 'new'
      end
     

end

def edit
    @quest = Quest.find(params[:id])

end


def update

    @quest = Quest.find(params[:id])

 
    if  @quest.update(quest_params)
        redirect_to @quest
    else
        render action: 'edit'
    end
end

def show
    @quest = Quest.find(params[:id])
    @players = Player.all
    @units = @quest.units.all


  
end

def destroy
    @quest = Quest.find(params[:id])
    @unit = params[unit]
    @unit.destroy


    redirect_to quest_path(@quest)
end

def index
    @quests = Quest.all
end









	def quest_params
    params.require(:quest).permit(
        :number,
    	:name,
    	:short_discription,
    	:description,
    	:difficulty,
    	:status,
    	:aligment,

    	:quantity,
    	:player,
    	:requirements,
    	:reward,
    	:penalty,
    



    	:have_opposite, 
    	:opposite_description, 
    	:opposite_requirements, 
    	:opposite_reward, 
    	:opposite_players, 
    	:opposite_aligment,


        :soldier,
        :missioner,
        :doctor,
        :cook,
        :seeman,
        :carpenter,
        :parlamenteer,
        :korrehidor,
        :trader,
        :maper,


        :op_soldier,
        :op_missioner,
        :op_doctor,
        :op_cook,
        :op_seeman,
        :op_carpenter,
        :op_parlamenteer,
        :op_korrehidor,
        :op_trader,
        :op_maper,
        :started_at




    	)
	end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController

  def create 
    @quest = Quest.find(params[:quest_id])
    @quest.units.create(unit_params)

    redirect_to quest_path(@quest)
  end

def destroy

	@quest = Quest.find(params[:quest_id])
 	@unit = @quest.units.find(params[:id])
    @unit.destroy


  	redirect_to quest_path(@quest)

end


  

  def unit_params
    params.require(:unit).permit(:name, :number, :player, :u_aligment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clist_helper.rb
module ClistHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DccCl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

<link rel="stylesheet" href="/css/stats.css">
<link rel="stylesheet" href="/css/navbar.css">


 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  




  </head>

  <body>
    <%if user_signed_in? %>
    <h3>Привет, <%=current_user.email%>.
    Твое мировоззрение: <%=current_user.aligment%>. Твой уровень доступа: <%=current_user.level%></h3>
    <hr/>
<%end%>
    <a class="nav-link active" aria-current="page" href=<%=quests_url%>><h2>Все квесты</h2></a>
    <input  type="button" onclick="history.back();" value="Назад"/>
  
    <!--<a class="nav-link" href="#"></a>
 
    <a class="nav-link" href="#">Link</a>

    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
<hr/>

    <%= yield %>

    <script src="/js/stats.js"></script>
    <script src="/js/dynamic.js"></script>

  </body>
</html>

app/views/quests/index.html.erb
<html lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" href="style.css" type="text/css" />
    <script src="Hyphenator.js" type="text/javascript"></script>
  </head>

  <body >

    <h1>Эпоха королей</h1>


      <p class="dropcap">
			Описание работы ресурса и как создавать и брать квесты
      </p>

      <p>
       <!-- Nam dolor mauris, condimentum a neque vitae, eleifend interdum dolor.-->
      </p>

      <label >
       Список квестов
        <table>
          <tr>
          	<th>
              Номер
            </th>
            <th>
              Название
            </th>
             <th>
              Статус
            </th>
               <th>
              Взять
            </th>
          </tr>


        <% @quests.each do |quest| %>
          <tr>
            
            <td>
              <%= quest.id %>
            </td>
            <td>
              <%= quest.name %>
            </td>

              <td>
              <%= quest.status %>
            </td>
            <td>
              <a class="button button-primary cta" href=<%=edit_quest_url(quest)%>><h2>Открыть</h2></a>
            </td>

          </tr>
          <%end%>

          <tr>
            <td>
            </td>
             <td>
       
            </td>
            <td>
            </td>
            <td>
            <a class="button button-primary cta" href=<%=new_quest_url(@quest)%>><h2>Добавить квест</h2></a>
            </td>
          </tr>

        </table>
      </label>

     

     <!-- <p>
        Donec nisl mi, dictum at sapien aliquet, efficitur iaculis odio.
        Morbi at semper nisl, in ultrices nibh. Nunc venenatis scelerisque erat,
        iaculis semper dolor fringilla sed.
      </p>
      
      <div class="readaloud">
        Text in boxes like these are meant to be read aloud or paraphrased to
        players as they first arrive at a location or given specific conditions
        described in the text.
      </div>

      <h3>About sub-subs</h3>
      
      <div class="opening-flavour">
        Sub-subs, h3s, or sections of sections of chapters perhaps
      </div>

      <p>
        Fusce vehicula placerat ullamcorper.
        Praesent dui risus, interdum at eros sit amet, mattis volutpat nunc.
      </p>

      <p>
        You can sub-divide sections even further to explain more minor point.
        Like if you want to explain about different kinds of movement.
      </p>

      <h4>Burrow</h4>
      
      <p>
        Curabitur rutrum non diam in eleifend.
      </p>

      <h4>Climb</h4>
      
      <p>
        Nulla gravida dui et ipsum iaculis eleifend.
      </p>

      <h4>Fly</h4>

      <p>
        Aenean volutpat, nisi in pellentesque consectetur, dui mauris tempor
        sapien, non volutpat quam quam id arcu.
      </p>

      <p>
        Below is a list of some creatures that can fly:
      </p>

      <p>
        <strong>Unladen Swallows</strong> can fly.
        Some have even been known to carry coconuts over long distances.
      </p>

      <p>
        <strong>Bees</strong> can fly too. They like birds, so sometimes they
        fly together.
      </p>

      <p>
        <strong>Penguins</strong> can fly too if they swim really fast first.
      </p>

      <p>
        Fusce maximus lacus pulvinar augue venenatis, sed ullamcorper odio gravida.
        Maecenas nec dapibus elit, et faucibus enim.
        Nulla auctor viverra orci ac tempor.
        Mauris fringilla rhoncus nibh, quis volutpat velit vehicula et.
      </p>
      
      <div class="sidenote">
        <h4>Sidenotes</h4>
        
        <p>
          Sometimes we might have asides to include.
        </p>

        <p>
          This is the kind of place we can put them.
        </p>
      </div>

      <div class="page-break"></div>

      <h2>More styles</h2>

      <p class="dropcap">
        More styles are available, like the ones shown below,
        including lists, quotes, and alternative colouring and layout.
      </p>

      <h3 class="blue-head">Alternative header</h3>

      <p>
        Colours that work really well include:
      </p>
      
      <ul>
        <li>
          Burgundy
        </li>
        <li>
          Brown
        </li>
        <li>
          Golden
        </li>
        <li>
          Grey
        </li>
      </ul>

      <p>
        Don't quote me on that though.
      </p>

      <blockquote>
        <p>
          This is the single best thing since sliced bread. Perhaps.
        </p>

        <cite>
          The Author, <i>The Scriptures</i>
        </cite>
      </blockquote>

  -->
 

  </body>
</html>

app/views/quests/show.html.erb
<html lang="en">

  <head>

    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  
    
  </head>

  <body>
<div>
    <h1><%=@quest.name%></h1>
<%if @quest.started_at != nil %>

    <%if @quest.started_at.strftime("%s").to_i > Time.now.strftime("%s").to_i %>

<p2> Осталось до начала квеста: <%=Time.at(@quest.started_at.strftime("%s").to_i - Time.now.strftime("%s").to_i).utc.strftime("%H ч. %M м.")%> </p2>



<%end%>
<%end%>
 

    <h3><h2>Количество игроков: </h2></h3>

<%@a = "sleep"%>
<%@op_a = "sleep"%>

          
          
  <% if @quest.status == "wake" and @quest.aligment == "Законный" %>
  <% @a = "good"%>
  <%elsif @quest.status == "active" and @quest.aligment == "Противозаконный"%> 
    <% @a = "good"%>
    <%end%>
<!-- Добавление игроков -->

<% if @a == "good" %>
<table>
          <tr>
            <th>
              Номер наемника
            </th>
            <th>
              Номер игрока
            </th>
            <th>
              Уволить
            </th>

          </tr>
<%if @quest.soldier != nil %>
        
        <%@arr = Array.new%>
        <%@players.each do |player| %>
            <%@arr  << [player.number]  %>
        <%end%>
        <%@i = 1 %>
        
        
            <%@quest.soldier.times do %></p3>
            <tr>
               <%@unit = @units.where(number:@i,name:"солдат", u_aligment:"good").take%>
                <% if @unit != nil %>
                     <td>
                        <%=@unit.number %>
                            
                    </td>
                    <td>
                    <%=@unit.player %></td>
                    <td>
                    <%= link_to 'Уволить',  quest_unit_path(@unit.quest, @unit),   method: :delete, data: { confirm: 'Точно?' } %></td>
                                        <%@i+=1%>
</tr>
                <%else%>
                        <%= form_for ([@quest, @quest.units.build]) do |f| %>
                        <tr>
                                           <td>
                                            <%= @i%>
                                                
                                            </td>

                                          <td> 
                                           <%=  f.hidden_field :name, value: "солдат"%>
                                            <%= f.hidden_field :number, value: @i  %>
                                            <%= f.hidden_field :u_aligment, value: "good" %>
                                            <!--<%= f.select :player, @arr %>-->
                                            <!--<%= f.submit  'нанять'%>-->
                                            <%= f.select :player, @arr, { class: 'form-control'}, :onchange => 'this.form.submit()' %>
                                        </td>
                                            <%@i+=1%>
                                        <td>
                                                Нанят
                                        </td>
                                    </tr>
            <%end%>
                      

        <%end%>
  
    <%end%>
 
    <%end%>      
</table>    






    <%end%>
</div>
    <%if @quest.soldier != nil %>
    <p3>  <%=@quest.soldier%> чел.</p3>
    <%end%>
    <!--
    <%if @quest.missioner != 0 %>
    <p3> Миссионер: <%=@quest.missioner%> чел.</p3>
    <%end%>
    <%if @quest.doctor != 0 %>
    <p3> Лекарь: <%=@quest.doctor%> чел.</p3>
    <%end%>
    <%if @quest.cook != 0 %>
    <p3> Кок: <%=@quest.cook%> чел.</p3>
    <%end%>
    <%if @quest.seeman != 0 %>
    <p3> Моряк: <%=@quest.seeman%> чел.</p3>
    <%end%>
    <%if @quest.carpenter != 0 %>
    <p3> Плотник: <%=@quest.carpenter%> чел.</p3>
    <%end%>
    <%if @quest.parlamenteer != 0 %>
    <p3> Парламентер: <%=@quest.parlamenteer%> чел.</p3>
    <%end%>
    <%if @quest.korrehidor != 0 %>
    <p3> Коррехидор: <%=@quest.korrehidor%> чел.</p3>
    <%end%>
    <%if @quest.trader != 0 %>
    <p3> Торговец: <%=@quest.trader%> чел.</p3>
    <%end%>
    <%if @quest.maper != 0 %>
    <p3> Картограф: <%=@quest.maper%> чел.</p3>
    <%end%>

-->

    <h3>Тип задания</h3>
    <p3><%=@quest.short_discription%></p3>


    <h3>Описание квеста</h3>
    <p3><%=@quest.description%></p3>

    


    <h3>Законность</h3>
    <p3><%=@quest.aligment%> </p3>

    <h3>Особый предмет или фраза, которые нужно принести или произнести для выполнения</h3>
    <p3> <%=@quest.requirements%> </p3>


    <h3>Награда</h3>
    <p3><%=@quest.reward%></p3>
</div>










<%@quest.units.count%>

<% if @quest.soldier==@quest.units.count and @quest.status == "wake" %>

 

<a class="button button-primary cta" href=<%=edit_quest_path(@quest)%>><h2>Выдать</h2></a>

<% elsif @quest.status == "active" %>

<h2> Квест в процессе выполнения</h2>

<a class="button button-primary cta" href=<%=edit_quest_path(@quest)%>><h2>Принять</h2></a>


<%elsif @quest.status == "complete"%>

<h2> Квест выполнен</h2>

<a class="button button-primary cta" href=<%=quests_path%>><h2>Назад к списку</h2></a>

<%end%>







   <!-- Добавление солдатов -->

  <% if @quest.status == "wake" and @quest.aligment == "Противозаконный" %>
  <% @op_a = "bad"%>
  <%elsif @quest.status == "active" and @quest.aligment == "Законный"%> 
    <% @op_a = "bad"%>


    <%end%>

<%  if @op_a == "bad" %>
   <h2>Назначить бандитскую бригаду </h2>

<table>
          <tr>
            <th>
              Номер наемника
            </th>
            <th>
              Номер игрока
            </th>
            <th>
              Уволить
            </th>

          </tr>
<%if @quest.op_soldier != nil %>
        
        <%@arr = Array.new%>
        <%@players.each do |player| %>
            <%@arr  << [player.number]  %>
        <%end%>
        <%@i = 1 %>
        
        
            <%@quest.op_soldier.times do %></p3>
            <tr>
               <%@unit = @units.where(number:@i,name:"солдат", u_aligment:"bad").take%>
                <% if @unit != nil %>
                     <td>
                        <%=@unit.number %>
                            
                    </td>
                    <td>
                    <%=@unit.player %></td>
                    <td>
                    <%= link_to 'Уволить',  quest_unit_path(@unit.quest, @unit),   method: :delete, data: { confirm: 'Точно?' } %></td>
                                        <%@i+=1%>
</tr>
                <%else%>
                        <%= form_for ([@quest, @quest.units.build]) do |f| %>
                        <tr>
                                           <td>
                                            <%= @i%>
                                                
                                            </td>

                                          <td> 
                                           <%=  f.hidden_field :name, value: "солдат"%>
                                            <%= f.hidden_field :number, value: @i  %>
                                            <%= f.hidden_field :u_aligment, value: "bad" %>
                                            <!--<%= f.select :player, @arr %>-->
                                            <!--<%= f.submit  'нанять'%>-->
                                            <%= f.select :player, @arr, { class: 'form-control'}, :onchange => 'this.form.submit()' %>
                                        </td>
                                            <%@i+=1%>
                                        <td>
                                                Нанят
                                        </td>
                                    </tr>
            <%end%>
                      

        <%end%>
  
    <%end%>
 
    <%end%>      
</table>    

 

                <%@op_u = @quest.soldier%>

                <% if @quest.op_soldier==@quest.units.count-@op_u and @op_a = "bad"   %>
                    

                <a class="button button-primary cta" href=<%=edit_quest_path(@quest)%>><h2>Выдать Противозаконный квест</h2></a>
                <%end%>
<%end%>




               
</body>
</html>

app/views/quests/test.html.erb

   



 <!-- Добавление лекаря -->

            <%if @quest.op_doctor != 0 %>
                <%@op_d = 1%>
                <%@arr = Array.new%>
                        <%@players.each do |player| %>
                            <%@arr  << [player.number]  %>
                        <%end%>

                 <p3> Лекарь: <%@quest.op_doctor.times do %></p3><br/>
                        <%unit = @units.where(number:@op_d,name: "лекарь").take%>

                        <% if unit != nil %>
                        <p3><%=unit.number %>-й лекарь нанят, игрок №
                        <%=unit.player %></p3><br/>


                    <%= link_to 'Delete',  quest_unit_path(unit.quest, unit),   method: :delete, data: { confirm: 'Are you sure?' } %>

                        <%else%>

                        <%= form_for ([@quest, @quest.units.build]) do |f| %> 
                        <%= @op_d%><%=  f.hidden_field :name, value: "лекарь"%>
                        <%= f.hidden_field :number, value: @op_d %>
                        <%= f.select :player, @arr %>
                        <%= f.submit  'нанять'%>
                        <%end%>

                        <%end%>
                        <%@op_d+=1%>
                    <%end%>
                <%end%><br/><br/>

        <!-- Добавление кока -->

            <%if @quest.op_cook != 0 %>
                <%@op_c = 1%>
                <%@arr = Array.new%>
                        <%@players.each do |player| %>
                            <%@arr  << [player.number]  %>
                        <%end%>

                 <p3> Кок: <%@quest.op_cook.times do %></p3><br/>
                        <%unit = @units.where(number:@op_c,name: "кок").take%>

                        <% if unit != nil %>
                        <p3><%=unit.number %>-й лекарь нанят, игрок №
                        <%=unit.player %></p3><br/>


                    <%= link_to 'Delete',  quest_unit_path(unit.quest, unit),   method: :delete, data: { confirm: 'Are you sure?' } %>

                        <%else%>

                        <%= form_for ([@quest, @quest.units.build]) do |f| %> 
                        <%= @op_c%><%=  f.hidden_field :name, value: "кок"%>
                        <%= f.hidden_field :number, value: @op_c %>
                        <%= f.select :player, @arr %>
                        <%= f.submit  'нанять'%>
                        <%end%>

                        <%end%>
                        <%@op_c+=1%>
                    <%end%>
                <%end%><br/><br/>


        <!-- Добавление моряка -->

            <%if @quest.op_seeman != 0 %>
                <%@op_s = 1%>
                <%@arr = Array.new%>
                        <%@players.each do |player| %>
                            <%@arr  << [player.number]  %>
                        <%end%>

                 <p3> Моряк: <%@quest.op_seeman.times do %></p3><br/>
                        <%unit = @units.where(number:@op_s,name: "моряк").take%>

                        <% if unit != nil %>
                        <p3><%=unit.number %>-й моряк нанят, игрок №
                        <%=unit.player %></p3><br/>


                    <%= link_to 'Delete',  quest_unit_path(unit.quest, unit),   method: :delete, data: { confirm: 'Are you sure?' } %>

                        <%else%>

                        <%= form_for ([@quest, @quest.units.build]) do |f| %> 
                        <%= @op_s%><%=  f.hidden_field :name, value: "моряк"%>
                        <%= f.hidden_field :number, value: @op_s %>
                        <%= f.select :player, @arr %>
                        <%= f.submit  'нанять'%>
                        <%end%>

                        <%end%>
                        <%@op_s+=1%>
                    <%end%>
                <%end%><br/><br/>
        
<!-- Добавление плотника -->

            <%if @quest.op_carpenter != 0 %>
                <%@op_cp = 1%>
                <%@arr = Array.new%>
                        <%@players.each do |player| %>
                            <%@arr  << [player.number]  %>
                        <%end%>

                 <p3> Плотник: <%@quest.op_carpenter.times do %></p3><br/>
                        <%unit = @units.where(number:@op_cp,name: "плотник").take%>

                        <% if unit != nil %>
                        <p3><%=unit.number %>-й плотник нанят, игрок №
                        <%=unit.player %></p3><br/>


                    <%= link_to 'Delete',  quest_unit_path(unit.quest, unit),   method: :delete, data: { confirm: 'Are you sure?' } %>

                        <%else%>

                        <%= form_for ([@quest, @quest.units.build]) do |f| %> 
                        <%= @op_cp%><%=  f.hidden_field :name, value: "плотник"%>
                        <%= f.hidden_field :number, value: @op_cp %>
                        <%= f.select :player, @arr %>
                        <%= f.submit  'нанять'%>
                        <%end%>

                        <%end%>
                        <%@op_cp+=1%>
                    <%end%>
                <%end%><br/><br/>

<!-- Добавление парламентера -->

            <%if @quest.op_parlamenteer != 0 %>
                <%@op_p = 1%>
                <%@arr = Array.new%>
                        <%@op_players.each do |player| %>
                            <%@arr  << [player.number]  %>
                        <%end%>

                 <p3> Парламентер: <%@quest.op_parlamenteer.times do %></p3><br/>
                        <%unit = @units.where(number:@op_p,name: "парламентер").take%>

                        <% if unit != nil %>
                        <p3><%=unit.number %>-й парламентер нанят, игрок №
                        <%=unit.player %></p3><br/>


                    <%= link_to 'Delete',  quest_unit_path(unit.quest, unit),   method: :delete, data: { confirm: 'Are you sure?' } %>

                        <%else%>

                        <%= form_for ([@quest, @quest.units.build]) do |f| %> 
                        <%= @op_p%><%=  f.hidden_field :name, value: "парламентер"%>
                        <%= f.hidden_field :number, value: @op_p %>
                        <%= f.select :player, @arr %>
                        <%= f.submit  'нанять'%>
                        <%end%>

                        <%end%>
                        <%@op_p+=1%>
                    <%end%>
                <%end%><br/><br/>
        
<!-- Добавление коррехидора -->

            <%if @quest.op_korrehidor != 0 %>
                <%@op_k = 1%>
                <%@arr = Array.new%>
                        <%@players.each do |player| %>
                            <%@arr  << [player.number]  %>
                        <%end%>

                 <p3> Коррехидор: <%@quest.op_korrehidor.times do %></p3><br/>
                        <%unit = @units.where(number:@op_k,name: "коррехидор").take%>

                        <% if unit != nil %>
                        <p3><%=unit.number %>-й парламентер нанят, игрок №
                        <%=unit.player %></p3><br/>


                    <%= link_to 'Delete',  quest_unit_path(unit.quest, unit),   method: :delete, data: { confirm: 'Are you sure?' } %>

                        <%else%>

                        <%= form_for ([@quest, @quest.units.build]) do |f| %> 
                        <%= @op_k%><%=  f.hidden_field :name, value: "коррехидор"%>
                        <%= f.hidden_field :number, value: @op_k %>
                        <%= f.select :player, @arr %>
                        <%= f.submit  'нанять'%>
                        <%end%>

                        <%end%>
                        <%@op_k+=1%>
                    <%end%>
                <%end%><br/><br/>
        
<!-- Добавление торговца -->

            <%if @quest.trader != 0 %>
                <%@op_t = 1%>
                <%@arr = Array.new%>
                        <%@players.each do |player| %>
                            <%@arr  << [player.number]  %>
                        <%end%>

                 <p3> Торговец: <%@quest.trader.times do %></p3><br/>
                        <%unit = @units.where(number:@op_t,name: "торговец").take%>

                        <% if unit != nil %>
                        <p3><%=unit.number %>-й парламентер нанят, игрок №
                        <%=unit.player %></p3><br/>


                    <%= link_to 'Delete',  quest_unit_path(unit.quest, unit),   method: :delete, data: { confirm: 'Are you sure?' } %>

                        <%else%>

                        <%= form_for ([@quest, @quest.units.build]) do |f| %> 
                        <%= @op_t%><%=  f.hidden_field :name, value: "торговец"%>
                        <%= f.hidden_field :number, value: @op_t %>
                        <%= f.select :player, @arr %>
                        <%= f.submit  'нанять'%>
                        <%end%>

                        <%end%>
                        <%@op_t+=1%>
                    <%end%>
                <%end%><br/><br/>
        




<!-- Добавление картографа -->

            <%if @quest.op_maper != 0 %>
                <%@op_ma = 1%>
                <%@arr = Array.new%>
                        <%@players.each do |player| %>
                            <%@arr  << [player.number]  %>
                        <%end%>

                 <p3> Картограф: <%@quest.op_maper.times do %></p3><br/>
                        <%unit = @units.where(number:@op_ma,name: "картограф").take%>

                        <% if unit != nil %>
                        <p3><%=unit.number %>-й парламентер нанят, игрок №
                        <%=unit.player %></p3><br/>


                    <%= link_to 'Delete',  quest_unit_path(unit.quest, unit),   method: :delete, data: { confirm: 'Are you sure?' } %>

                        <%else%>

                        <%= form_for ([@quest, @quest.units.build]) do |f| %> 
                        <%= @op_ma%><%=  f.hidden_field :name, value: "картограф"%>
                        <%= f.hidden_field :number, value: @op_ma %>
                        <%= f.select :player, @arr %>
                        <%= f.submit  'нанять'%>
                        <%end%>

                        <%end%>
                        <%@op_ma+=1%>
                    <%end%>
                <%end%><br/><br/>
        
    <%if @quest.maper != 0 %>
    <p3> Картограф: <%=@quest.maper%> чел.</p3>
    <%end%>






    <%end%>